name: Sumania
version: '1.0-SNAPSHOT'
main: ch.retaxo.sumania.Sumania
api-version: '1.21'
description: 'Ein umfassendes SMP-Server-Plugin mit Wirtschaft, Teleportation, Claims und mehr.'
authors: [retaxo]

commands:
  sumania:
    description: Hauptbefehl des Plugins
    usage: /sumania [reload]
    permission: sumania.admin
  
  # Economy commands
  balance:
    description: Prüfe dein Guthaben
    usage: /balance [Spieler]
    aliases: [bal, money, geld, konto]
    permission: sumania.economy.balance
  pay:
    description: Bezahle einen anderen Spieler
    usage: /pay <Spieler> <Betrag>
    aliases: [bezahlen, zahlen]
    permission: sumania.economy.pay
  eco:
    description: Admin-Wirtschaftsbefehle
    usage: /eco <set|add|remove|get> <Spieler> <Betrag>
    permission: sumania.economy.admin
  bal:
    description: Prüfe dein Guthaben (Kurzform)
    usage: /bal [Spieler]
    permission: sumania.economy.balance
  
  # Teleport commands
  tp:
    description: Teleportiere zu einem Spieler
    usage: /tp <Spieler> [Ziel]
    permission: sumania.teleport.tp
  tpa:
    description: Anfrage, sich zu einem Spieler zu teleportieren
    usage: /tpa <Spieler>
    permission: sumania.teleport.tpa
  tpaccept:
    description: Akzeptiere eine Teleportanfrage
    usage: /tpaccept
    aliases: [tpja]
    permission: sumania.teleport.tpaccept
  tpdeny:
    description: Lehne eine Teleportanfrage ab
    usage: /tpdeny
    aliases: [tpnein]
    permission: sumania.teleport.tpdeny
  
  # Home commands
  home:
    description: Teleportiere zu deinem Zuhause
    usage: /home [Name]
    aliases: [zuhause]
    permission: sumania.home.home
  sethome:
    description: Setze dein Zuhause
    usage: /sethome [Name]
    aliases: [setzuhause]
    permission: sumania.home.set
  delhome:
    description: Lösche dein Zuhause
    usage: /delhome [Name]
    aliases: [delzuhause, löschezuhause, löschehome]
    permission: sumania.home.delete
  homes:
    description: Liste deine Zuhause auf
    usage: /homes
    aliases: [zuhause-liste, homelist]
    permission: sumania.home.list
  
  # Warp commands
  warp:
    description: Teleportiere zu einem Warp
    usage: /warp <Name>
    permission: sumania.warp.use
  setwarp:
    description: Setze einen Warp
    usage: /setwarp <Name>
    permission: sumania.warp.set
  delwarp:
    description: Lösche einen Warp
    usage: /delwarp <Name>
    permission: sumania.warp.delete
  warps:
    description: Liste alle Warps auf
    usage: /warps
    aliases: [warplist]
    permission: sumania.warp.list
  warpmenu:
    description: Öffne das Warp-Menü
    usage: /warpmenu
    aliases: [wm, warps-menu]
    permission: sumania.warp.menu
  
  # Chat commands
  chat:
    description: Chat-Verwaltungsbefehle
    usage: /chat [mute|unmute|clear]
    permission: sumania.chat
    
  # Discord commands
  discord:
    description: Discord-Verknüpfungsbefehle
    usage: /discord [link|unlink]
    aliases: [dc]
    permission: sumania.discord
    
  # Shop commands
  shop:
    description: Öffne den Shop
    usage: /shop [Kategorie]
    aliases: [store, markt, laden]
    permission: sumania.shop
    
  # Lottery commands
  lottery:
    description: Verlosungsbefehle
    usage: /lottery [buy|info]
    aliases: [verlosung, lotto]
    permission: sumania.lottery
    
  # Rewards commands
  rewards:
    description: Belohnungsbefehle
    usage: /rewards [daily|weekly|monthly]
    aliases: [belohnungen, reward, belohnung]
    permission: sumania.rewards
    
  # Ban commands
  ban:
    description: Spieler permanent bannen
    usage: /ban <Spieler> <Grund>
    permission: sumania.ban
  tempban:
    description: Spieler temporär bannen
    usage: /tempban <Spieler> <Dauer> <Grund>
    aliases: [tban]
    permission: sumania.ban
  unban:
    description: Spieler entbannen
    usage: /unban <Spieler>
    permission: sumania.ban
  lookup:
    description: Spielerinformationen anzeigen
    usage: /lookup <Spieler>
    permission: sumania.lookup

permissions:
  sumania.admin:
    description: Erlaubt Zugriff auf Admin-Befehle
    default: op
  sumania.admin.reload:
    description: Erlaubt das Neuladen des Plugins
    default: op
  
  # Economy permissions
  sumania.economy.balance:
    description: Erlaubt das Prüfen des eigenen Guthabens
    default: true
  sumania.economy.balance.others:
    description: Erlaubt das Prüfen des Guthabens anderer Spieler
    default: op
  sumania.economy.pay:
    description: Erlaubt das Bezahlen anderer Spieler
    default: true
  sumania.economy.admin:
    description: Erlaubt das Verwalten der Wirtschaft
    default: op
  
  # Teleport permissions
  sumania.teleport.tp:
    description: Erlaubt das Teleportieren zu anderen Spielern
    default: op
  sumania.teleport.tp.others:
    description: Erlaubt das Teleportieren anderer Spieler
    default: op
  sumania.teleport.tpa:
    description: Erlaubt das Anfragen von Teleportationen zu anderen Spielern
    default: true
  sumania.teleport.tpaccept:
    description: Erlaubt das Akzeptieren von Teleportanfragen
    default: true
  sumania.teleport.tpdeny:
    description: Erlaubt das Ablehnen von Teleportanfragen
    default: true
  
  # Home permissions
  sumania.home.home:
    description: Erlaubt das Teleportieren zu Zuhause
    default: true
  sumania.home.set:
    description: Erlaubt das Setzen von Zuhause
    default: true
  sumania.home.delete:
    description: Erlaubt das Löschen von Zuhause
    default: true
  sumania.home.list:
    description: Erlaubt das Auflisten von Zuhause
    default: true
  sumania.home.bypass.limit:
    description: Erlaubt das Umgehen des Zuhause-Limits
    default: op
  
  # Warp permissions
  sumania.warp.use:
    description: Erlaubt die Verwendung von Warps
    default: true
  sumania.warp.use.*:
    description: Erlaubt die Verwendung aller Warps
    default: true
  sumania.warp.set:
    description: Erlaubt das Setzen von Warps
    default: op
  sumania.warp.delete:
    description: Erlaubt das Löschen von Warps
    default: op
  sumania.warp.list:
    description: Erlaubt das Auflisten von Warps
    default: true
  sumania.warp.menu:
    description: Erlaubt das Öffnen des Warp-Menüs
    default: true
  
  # Chat permissions
  sumania.chat:
    description: Erlaubt Zugriff auf Chat-Befehle
    default: true
  sumania.chat.mute:
    description: Erlaubt das Stummschalten und Aktivieren des Chats
    default: op
  sumania.chat.clear:
    description: Erlaubt das Löschen des Chats
    default: op
  sumania.chat.bypass.mute:
    description: Erlaubt das Sprechen im stummen Chat
    default: op
  sumania.chat.bypass.cooldown:
    description: Erlaubt das Umgehen der Chat-Abklingzeit
    default: op
    
  # Discord permissions
  sumania.discord:
    description: Erlaubt Zugriff auf Discord-Befehle
    default: true
    
  # Shop permissions
  sumania.shop:
    description: Erlaubt Zugriff auf den Shop
    default: true
  sumania.shop.admin:
    description: Erlaubt das Verwalten des Shops
    default: op
    
  # Lottery permissions
  sumania.lottery:
    description: Erlaubt Zugriff auf Verlosungsbefehle
    default: true
  sumania.lottery.admin:
    description: Erlaubt das Verwalten der Verlosung
    default: op
    
  # Rewards permissions
  sumania.rewards:
    description: Erlaubt Zugriff auf Belohnungsbefehle
    default: true
  sumania.rewards.admin:
    description: Erlaubt das Verwalten der Belohnungen
    default: op
    
  # Ban permissions
  sumania.ban:
    description: Erlaubt das Bannen und Entbannen von Spielern
    default: op
  sumania.lookup:
    description: Erlaubt das Anzeigen von Spielerinformationen
    default: op
